version: '3'

services:
  broker-service:
    image: docker.io/luanvieiraavmb/broker-service:latest
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: docker.io/luanvieiraavmb/authentication-service:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: docker.io/luanvieiraavmb/logger-service:latest
    deploy:
      mode: replicated
      replicas: 1
    
  mail-service:
    image: docker.io/luanvieiraavmb/mail-service:latest
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: none
      FROM_NAME: John Doe
      FROM_ADDRESS: john.doe@avmb.com.br

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    deploy:
      mode: global

  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - "27017:27017"
    restart: always
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/